version: '3.4'

services:
  registry:
    image: verdaccio/verdaccio:4.5.1
    volumes:
      - ./config.yaml:/verdaccio/conf/config.yaml
      - ./htpasswd:/verdaccio/storage/htpasswd
    ports:
      - 4873:4873
